### ISSUE TITLE
Wrong image names in README.md

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [InformaticsMatters/docker-rdkit#1]
docker image names in README.me examples are not correct. For example:

 informaticsmatters/rdkit_java_debian:latest 

should be:

 informaticsmatters/rdkit-java-debian:latest

**Comment by tdudgeon** [comment]
Thanks. Good spot. 
I updated the README. Hopefully it's better now.
Could you check it over?

**Comment by OriolLopezMassaguer** [comment]
Correct!
