### ISSUE TITLE
ARM64 Support possible?

### ISSUE THREAD

**Issue by artran** [InformaticsMatters/docker-rdkit#5]
Hi,
I've been trying to get this container to build on an ARM64 platform but I get a variety of errors. I know you aren't currently claiming to support ARM64 but do you have any plans for it in the future?

**Comment by tdudgeon** [comment]
We've not got any plans at present, but clearly it would be useful.
More fundamentally I'd need to find out if RDKit itself can run on ARM64, which I'm not sure about.

**Comment by artran** [comment]
OK, I've been able to run RDKit on ARM64 using Conda so it is definitely possible. Unfortunately they haven't got around to making the Conda package for RDKit-Postgres yet.

I've forked this project and will have a go at getting it to compile but I'm not much of a C programmer so I might not get very far. I'll feed back any progress to you so that you can include it if you want to.

**Comment by artran** [comment]
I've managed to get a working ARM64 build for Debian and I'm checking it out in one of my projects. The changes were pretty minimal so I'll let you know what is needed once I've verified it is all OK

**Comment by willfinnigan** [comment]
I'd be really interested in using an ARM64 docker image for the Postgres cartridge

**Comment by artran** [comment]
> I'd be really interested in using an ARM64 docker image for the Postgres cartridge

My fork works for me but I need to check I've pushed everything.

The work was mostly changing `docker build` to `docker buildx build` and changing a couple of flags that are specific to x86. IIRC I've only updated the build for debian.

**Comment by willfinnigan** [comment]
Hi Artran,

Thanks for publishing your changes to your fork.  When I try build-debian.sh and run I get the error `docker exporter does not currently support exporting manifest lists`.  I only know enough of docker to get by so I'm a bit stumped by that one.

**Comment by artran** [comment]
> Thanks for publishing your changes to your fork. When I try build-debian.sh and run I get the error `docker exporter does not currently support exporting manifest lists`. I only know enough of docker to get by so I'm a bit stumped by that one.

Yep, that was a change I had made but not pushed yet. I've just pushed the code that works for me. The issue is to do with buildx not being able to load multiple architectures, I think. What I've now got it doing is pushing the images to my docker account (change the BASE in `params.sh` to your account).

If it's just the RDKit cartridge then I think `docker pull artran/rdkit-cartridge-debian:Release_2020_03` might work for you.

**Comment by willfinnigan** [comment]
Awesome thanks.  You're pre-built docker container is working nicely thanks.   

Just FYI,  I tried to run `build-debian.sh` for your new code and I get a different error now:  `error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")`

**Comment by artran** [comment]
> Awesome thanks. You're pre-built docker container is working nicely thanks.

Brilliant, glad I could help.

> 
> Just FYI, I tried to run `build-debian.sh` for your new code and I get a different error now: `error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")`

Yes, that's just the way to build multi-platform in docker. I'll add a readme or something when I get a minute.

**Comment by willfinnigan** [comment]
Ah I see.  I'll need to learn more about building for multiple platforms now I'm on an M1 chip.  Thanks for the help!

**Comment by tdudgeon** [comment]
@artran Do you think your ARM support should be merged back into my repo, or should it remain a fork?
I'm happy to merge the changes if they don't impact the building the current images and you would be willing to continue to handle the ARM side of things.

**Comment by artran** [comment]
> @artran Do you think your ARM support should be merged back into my repo, or should it remain a fork?
> I'm happy to merge the changes if they don't impact the building the current images and you would be willing to continue to handle the ARM side of things.

@tdudgeon I think merging my changes in would be best as I doubt that I can keep a fork up to date as you improve this repo. There is a little bit of work to do to make it possible to merge my changes in, I think, so I'll have a go at getting it into a fit state. I'll do a pull request at some point soon.

**Comment by tdudgeon** [comment]
@artran I'm wanting to start to build "official" images with ARM support now.
What is the state of your fork? Should I pull it in now or are there updates you should do first?

**Comment by artran** [comment]
Hi Tim,
I haven't worked on my fork in about a year as the team I was building it for switched over to
using the Python package from PyPi. The only relevant changes I had made were to make one
of the compilation flags optional because ARM doesn't support it.

I'd be happy to share those commits if you feel it's woprthwhile.

Cheers, 
--
Ray Tran
***@***.*** ***@***.***>

**Comment by nmunro** [comment]
@tdudgeon I work with @artran and if it's ok, I'm going to be taking over this work, if providing an official image with arm support is still something you're considering doing?

**Comment by tdudgeon** [comment]
@nmunro Absolutely yes! What do we need to do?

**Comment by nmunro** [comment]
I'm going to merge the changes @artran made into my fork of this project and begin having a look from there

**Comment by nmunro** [comment]
@tdudgeon As I'm familiarising myself with this, I'm assuming that running `./build-debian.sh` or `./build-centos.sh` should build everything that is required and they're the entry point for this project?

**Comment by tdudgeon** [comment]
Yes, use the Debian one initially. I don’t keep the centos one up to data at the moment.
The `params.sh` file is what configures things. Specific RDKit versions are built from the various branches, with their own params.sh. The `master` branch builds the latest RDKit, which sometimes fails because of changes in RDKit.

**Comment by nmunro** [comment]
I've opened a draft pull request for your consideration, I'm having some network issues pushing it to docker hub, but the build appears to be successful.

**Comment by tdudgeon** [comment]
ARM64 support is implemented and will happen for all future builds
