### ISSUE TITLE
Debian Dockerfile Build "/usr/share/postgresql/15/extension/rdkit.control": No such file or directory.

### ISSUE THREAD

**Issue by hdj-elixirsoftware** [InformaticsMatters/docker-rdkit#7]
**Description**

I’m encountering issues with PostgreSQL failing to locate the RDKit extension due to path changes. This issue started occurring after the latest change, commit `c12372b`, which looks to have updated the Postgres, Boost and Debian versions for the base image.

**Error Details**

When attempting to use the RDKit cartridge extension in PostgreSQL, the following error appears:
```
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/rdkit.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

**Steps Taken to Attempt to Remediate**

1. Copying Files: Attempted to copy the RDKit extension files from the PostgreSQL 17 directory to the PostgreSQL 15 directory to restore compatibility - successful build but unable to use extension successfully.
2. Updating Dockerfile: Forked the repository and attempted to upgrade the cartridge image `PG_MAJOR` value to use PostgreSQL 17 - unable to build.
3. Pinning the image used to `rdkit-cartridge-debian:Release_2024_03_3` - builds and rdkit extensions found as expected.

Is the change made in order to support an updated version of the rdkit library and/or version of postgres that has become the required version?

**Comment by tdudgeon** [comment]
Yes, I'm updating images as we speak.
You are working on `master` branch?
I which case, yes, there have just been updates to postgres, boost and swig, which might explain the problems you are seeing.
I would advise on not using the `latest` versions as they will be unpredictable. Instead use the versioned ones e.g. the `informaticsmatters/rdkit-cartridge-debian:Release_2024_03_4` container image.
If you need to build then yourself then switch to the appropriate branch.

**Comment by tdudgeon** [comment]
And I think I've spotted the error on master. Will fix soon.

**Comment by hdj-elixirsoftware** [comment]
That's great thanks! Yeah I've pinned the version I use to `rdkit-cartridge-debian:Release_2024_03_3` for now. Previously it wasn't for some reason.

**Comment by tdudgeon** [comment]
The latest cartridge image (from master branch) should now be working again.

**Comment by hdj-elixirsoftware** [comment]
Thanks for doing this - it's much appreciated!!!
